version: 2
updates:
  - package-ecosystem: gomod
    directory: "/scsystem-api"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
  - package-ecosystem: npm
    directory: "/mobile"
    schedule:
      interval: daily
      time: "10:00"
    open-pull-requests-limit: 10
