version: '3.1'
services:
  api-server:
    image: asyncfiber:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    restart: always
    command: "./bin/exe s"
    networks:
      - bridge
    ports:
      - 8000:8000

  worker:
    image: asyncfiber:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.prod
    restart: always
    networks:
      - bridge
    command: "./bin/exe w"

  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - bridge
    command: /bin/sh -c "redis-server --requirepass password"
    environment:
      - REDIS_HOST_PASSWORD=password
    volumes:
      - ./data/redis:/data

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: kompose-db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    restart: on-failure:3
    networks:
      - bridge
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

networks:
  bridge:
volumes:
  data: