version: "3.1"
services:
  swipe-server:
    image: duchungho/swc-api:latest
    env_file:
      - .env.prod
    restart: always
    command: "swipe s"
    networks:
      - swipe_bridge
    ports:
      - 8000:8000

  swipe-worker:
    image: duchungho/swc-api:latest
    env_file:
      - .env.prod
    restart: always
    networks:
      - swipe_bridge
    command: "swipe w"

networks:
  swipe_bridge:
volumes:
  pkg:
