version: "3.1"
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    command: /bin/sh -c "redis-server --requirepass password"
    environment:
      - REDIS_HOST_PASSWORD=password
    volumes:
      - ./pkg/db/data/redis:/data
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: swc-db
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    ports:
      - 5432:5432
    restart: on-failure:3
    volumes:
      - ./pkg/db/data/postgres:/var/lib/postgresql/data
volumes:
  pkg:
