version: "3.1"
services:
  api-server:
    image: duchungho/swc-api:latest
    env_file:
      - .env.prod
    restart: always
    command: "swipe s"
    networks:
      - bridge
    ports:
      - 8000:8000

  worker:
    image: duchungho/swc-api:latest
    env_file:
      - .env.prod
    restart: always
    networks:
      - bridge
    command: "swipe w"

networks:
  bridge:
volumes:
  pkg:
