version: "3.1"
services:
  api-server:
    image: duchungho/swc-api:4b35adc
    restart: always
    command: "/bin/exe s"
    networks:
      - bridge
    ports:
      - 8000:8000
networks:
  bridge:
volumes:
  k8s:
