apiVersion: apps/v1
kind: Deployment
metadata:
  name: swc-api-deployment
  labels:
    app: swc-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swc-api
  template:
    metadata:
      labels:
        app: swc-api
    spec:
      containers:
        - image: duchungho/swc-api:latest
          name: swc-api-server
          env:
            - name: HOST
              valueFrom:
                secretKeyRef:
                  name: swc-api-secret
                  key: swc-api-host
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: swc-api-secret
                  key: swc-api-port
          command: ["swipe"]
          args: ["s"]
          ports:
            - containerPort: 8000
