apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: swc-api
spec:
  selector:
    app: swc-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
