basePath: /
definitions:
  domain.CartBodySchema:
    properties:
      amount:
        type: string
      category:
        type: string
      img:
        type: string
      product_name:
        type: string
      quantity:
        type: integer
    type: object
  domain.CartInsertReq:
    properties:
      inventory_id:
        type: integer
      quantity:
        type: integer
      user_id:
        type: integer
    required:
    - inventory_id
    - quantity
    - user_id
    type: object
  domain.CartSchema:
    properties:
      products:
        items:
          $ref: '#/definitions/domain.CartBodySchema'
        type: array
      user_id:
        type: integer
    type: object
  domain.Categories:
    properties:
      description:
        type: string
      id:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
  domain.CategoriesSwagger:
    properties:
      description:
        type: string
      name:
        type: string
    required:
    - description
    - name
    type: object
  domain.CategorySlices:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Categories'
        type: array
    type: object
  domain.CollectionBodySwagger:
    properties:
      description:
        type: string
      subtitle:
        type: string
      text_color:
        type: string
      title:
        type: string
    required:
    - description
    - subtitle
    - text_color
    - title
    type: object
  domain.CollectionSchemaSwagger:
    properties:
      body:
        $ref: '#/definitions/domain.CollectionBodySwagger'
      headline:
        type: string
      position:
        type: string
    required:
    - body
    - headline
    - position
    type: object
  domain.CollectionUploadRes:
    properties:
      id:
        type: integer
      msg:
        type: string
    type: object
  domain.Collections:
    properties:
      card_banner:
        items:
          $ref: '#/definitions/domain.CollectionsBody'
        type: array
      headline:
        type: string
      position:
        type: string
    type: object
  domain.CollectionsBody:
    properties:
      created:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        type: string
      subtitle:
        type: string
      text_color:
        type: string
      title:
        type: string
    required:
    - description
    - subtitle
    - text_color
    - title
    type: object
  domain.Error:
    properties:
      msg:
        type: string
    type: object
  domain.InventorySchema:
    properties:
      available:
        type: string
      currency_code:
        type: string
      id:
        type: string
      model:
        type: string
      price:
        type: string
      product_id:
        type: string
      specs:
        $ref: '#/definitions/domain.SpecsDetail'
    required:
    - available
    - currency_code
    - model
    - price
    - product_id
    type: object
  domain.InventoryStruct:
    properties:
      available:
        type: string
      currency_code:
        type: string
      model:
        type: string
      price:
        type: string
      product_id:
        type: string
      specs:
        $ref: '#/definitions/domain.SpecsDetail'
    required:
    - available
    - currency_code
    - model
    - price
    - product_id
    type: object
  domain.LoginReq:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  domain.LoginRes:
    properties:
      email:
        type: string
      success:
        type: boolean
      token:
        type: string
    required:
    - email
    - success
    - token
    type: object
  domain.OK:
    properties:
      msg:
        type: string
    type: object
  domain.ProductReq:
    properties:
      RAM:
        items:
          type: integer
        type: array
      SSD:
        items:
          type: integer
        type: array
      category_id:
        type: string
      description:
        type: string
      display:
        type: string
      name:
        type: string
      price:
        type: string
      screen:
        type: string
      status:
        type: string
      supplier_id:
        type: string
    required:
    - category_id
    - description
    - name
    - price
    - status
    - supplier_id
    type: object
  domain.ProductRes:
    properties:
      created:
        type: string
      description:
        type: string
      id:
        type: integer
      image:
        items:
          type: string
        type: array
      is_spec:
        type: boolean
      name:
        type: string
      price:
        type: string
      spec:
        $ref: '#/definitions/domain.Specs'
      status:
        type: string
    type: object
  domain.ProductsRes:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.ProductRes'
        type: array
      limit:
        type: integer
      page:
        type: integer
    type: object
  domain.SignUpReq:
    properties:
      email:
        type: string
      first_name:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - phone_number
    type: object
  domain.SignUpRes:
    properties:
      msg:
        type: string
      success:
        type: boolean
    required:
    - msg
    - success
    type: object
  domain.Specs:
    properties:
      RAM:
        items:
          type: integer
        type: array
      SSD:
        items:
          type: integer
        type: array
      display:
        type: string
      screen:
        type: string
    type: object
  domain.SpecsDetail:
    properties:
      color:
        type: string
      color_image:
        type: string
      image:
        type: string
      ram:
        type: string
      ssd:
        type: string
    type: object
  domain.SupplierSlices:
    properties:
      data:
        items:
          $ref: '#/definitions/domain.Suppliers'
        type: array
    type: object
  domain.Suppliers:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
  domain.SuppliersReq:
    properties:
      city:
        type: string
      district:
        type: string
      email:
        type: string
      name:
        type: string
      street:
        type: string
      ward:
        type: string
    required:
    - email
    - name
    type: object
  domain.UploadProductRes:
    properties:
      id:
        type: integer
      msg:
        type: string
    type: object
  domain.UserInfo:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      image:
        type: string
      last_name:
        type: string
      phone_number:
        type: string
      role:
        type: string
      username:
        type: string
    required:
    - email
    - first_name
    - id
    - image
    - last_name
    - phone_number
    - role
    - username
    type: object
  domain.UserUpdate:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      phone_number:
        type: string
      username:
        type: string
    required:
    - email
    - first_name
    - id
    - last_name
    - phone_number
    - username
    type: object
info:
  contact: {}
  description: This is a documentation for the Swipe API
  title: Swipe API Documentation
  version: 1.0.0
paths:
  /auth:
    get:
      consumes:
      - application/json
      description: check email address before login
      parameters:
      - description: email address
        in: query
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - account_management
  /auth/login:
    post:
      consumes:
      - application/json
      description: Login account.
      parameters:
      - description: Login
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/domain.LoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.LoginRes'
      tags:
      - account_management
  /auth/logout:
    get:
      consumes:
      - application/json
      description: logout user from the service
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - account_management
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Register account for admin.
      parameters:
      - description: Sign Up
        in: body
        name: sign_up
        required: true
        schema:
          $ref: '#/definitions/domain.SignUpReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SignUpRes'
      tags:
      - account_management
  /categories:
    get:
      consumes:
      - application/json
      description: Get categories
      parameters:
      - description: limit number
        in: query
        name: limit
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CategorySlices'
      tags:
      - products
    post:
      consumes:
      - application/json
      description: Insert new category
      parameters:
      - description: Categories Request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/domain.CategoriesSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - products
  /collections:
    get:
      consumes:
      - application/json
      description: Create collections
      parameters:
      - description: position of collections
        in: query
        name: position
        required: true
        type: string
      - description: limit of cards banner slices
        in: query
        name: limit
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.Collections'
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: Create collections
      parameters:
      - description: collections Request
        in: body
        name: collection
        required: true
        schema:
          $ref: '#/definitions/domain.CollectionSchemaSwagger'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.CollectionUploadRes'
      tags:
      - posts
  /collections/img:
    put:
      consumes:
      - application/json
      description: Create collections
      parameters:
      - description: image of collections
        in: formData
        name: img
        required: true
        type: file
      - description: collections identifier
        in: formData
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - posts
  /common/healthcheck:
    get:
      consumes:
      - application/json
      description: health check api server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - common
  /common/worker:
    get:
      consumes:
      - application/json
      description: health check worker consume server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - common
  /inventory:
    get:
      consumes:
      - application/json
      description: Get product availability in inventory
      parameters:
      - description: product id
        in: query
        name: pid
        required: true
        type: number
      - description: ram
        in: query
        name: ram
        required: true
        type: number
      - description: ssd
        in: query
        name: ssd
        required: true
        type: number
      - description: color
        in: query
        name: color
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.InventorySchema'
      tags:
      - products
    post:
      consumes:
      - application/json
      description: add product to inventory
      parameters:
      - description: Inventory Request
        in: body
        name: InventoryStruct
        required: true
        schema:
          $ref: '#/definitions/domain.InventoryStruct'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - products
  /oauth2/login:
    get:
      consumes:
      - application/json
      description: Auth0 Login form.
      produces:
      - application/json
      responses:
        "200":
          description: OK
      tags:
      - common
  /products:
    delete:
      consumes:
      - application/json
      description: delete product by id
      parameters:
      - description: product id
        in: query
        name: pid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - products
    get:
      consumes:
      - application/json
      description: get product information
      parameters:
      - description: limit number of products
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.ProductsRes'
      tags:
      - products
    post:
      consumes:
      - application/json
      description: create new product
      parameters:
      - description: Product Request
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/domain.ProductReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UploadProductRes'
      tags:
      - products
  /products/img:
    post:
      consumes:
      - multipart/form-data
      description: Insert new product image
      parameters:
      - description: id of product
        in: query
        name: id
        required: true
        type: string
      - description: image of product
        in: formData
        name: img
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/domain.Error'
      tags:
      - products
  /purchase/carts:
    delete:
      consumes:
      - application/json
      description: delete item from carts
      parameters:
      - description: user id
        in: query
        name: uid
        required: true
        type: integer
      - description: inventory id
        in: query
        name: wid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - purchase
    get:
      consumes:
      - application/json
      description: get list of items from carts
      parameters:
      - description: user id
        in: query
        name: uid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.CartSchema'
      tags:
      - purchase
    post:
      consumes:
      - application/json
      description: add item to carts.
      parameters:
      - description: cart insert request
        in: body
        name: login
        required: true
        schema:
          $ref: '#/definitions/domain.CartInsertReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - purchase
  /suppliers:
    get:
      consumes:
      - application/json
      description: get suppliers information
      parameters:
      - description: limit number of suppliers
        in: query
        name: limit
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.SupplierSlices'
      tags:
      - products
    post:
      consumes:
      - application/json
      description: insert new suppliers information
      parameters:
      - description: Suppliers Request
        in: body
        name: SuppliersReq
        required: true
        schema:
          $ref: '#/definitions/domain.SuppliersReq'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - products
  /users:
    get:
      consumes:
      - application/json
      description: get information for users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.UserInfo'
      tags:
      - account_management
    put:
      consumes:
      - application/json
      description: update information for users.
      parameters:
      - description: Update User
        in: body
        name: UserInfo
        required: true
        schema:
          $ref: '#/definitions/domain.UserUpdate'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - account_management
  /users/image:
    put:
      consumes:
      - application/json
      description: update information for users.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/domain.OK'
      tags:
      - account_management
swagger: "2.0"
