name: Build test api server

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: test api server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Build the Go application
        run: go build -ldflags="-s -w" -o ./bin/exe ./cmd

      - name: Remove binaries
        run: rm -rf bin

  test:
    needs: [build]
    name: unit test common
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21

      - name: Unit test - common
        run: sh hack/cmd_test.sh common
